import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";

export type CallStatus = "OPEN" | "FILLED" | "CONFIRMED" | "COMPLETED" | "CANCELLED";
export type CallParticipantStatus = "ACTIVE" | "WAITLIST";
const SUPPORT_JOBS = new Set(["High Priest", "Bard", "Gypsy", "Biochemist (Plant)", "Doram (Support)", "Lord Knight"]);
export const GENERIC_ROLES = ["DPS"] as const;
export function requirementMatchesJob(requirement:string,job:string|null|undefined){if(!job)return false;if(requirement==="DPS")return !SUPPORT_JOBS.has(job);return requirement===job;}
export async function ensureCallTables(){await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "guild_calls" ("id" text PRIMARY KEY,"guild_id" text NOT NULL,"creator_user_id" text NOT NULL,"title" text NOT NULL,"description" text,"start_at" timestamptz NOT NULL,"status" text NOT NULL DEFAULT 'OPEN',"discord_webhook_url" text,"announced_at" timestamptz,"reminder_sent_at" timestamptz,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS "guild_calls_guild_start_idx" ON "guild_calls" ("guild_id","start_at"); CREATE TABLE IF NOT EXISTS "guild_call_requirements" ("id" text PRIMARY KEY,"call_id" text NOT NULL,"requirement" text NOT NULL,"quantity" integer NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS "guild_call_requirements_call_idx" ON "guild_call_requirements" ("call_id"); CREATE TABLE IF NOT EXISTS "guild_call_participants" ("id" text PRIMARY KEY,"call_id" text NOT NULL,"requirement_id" text NOT NULL,"member_id" text NOT NULL,"job" text,"status" text NOT NULL DEFAULT 'ACTIVE',"signed_up_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),UNIQUE ("call_id","member_id")); ALTER TABLE "guild_call_participants" ADD COLUMN IF NOT EXISTS "job" text; CREATE INDEX IF NOT EXISTS "guild_call_participants_call_idx" ON "guild_call_participants" ("call_id"); CREATE TABLE IF NOT EXISTS "guild_call_webhooks" ("guild_id" text PRIMARY KEY,"webhook_url" text NOT NULL,"updated_at" timestamptz NOT NULL DEFAULT now());`);}
export function newId(prefix:string){return `${prefix}_${randomUUID().replaceAll("-","")}`;}
export async function refreshCallStatus(callId:string){await ensureCallTables();const rows=await prisma.$queryRawUnsafe<Array<{required:bigint;active:bigint;status:string}>>(`SELECT COALESCE((SELECT SUM(quantity) FROM "guild_call_requirements" WHERE call_id=$1),0) required,COALESCE((SELECT COUNT(*) FROM "guild_call_participants" WHERE call_id=$1 AND status='ACTIVE'),0) active,(SELECT status FROM "guild_calls" WHERE id=$1) status`,callId);const row=rows[0];if(!row||["CANCELLED","COMPLETED"].includes(row.status))return row?.status as CallStatus|undefined;const next=Number(row.active)>=Number(row.required)?"FILLED":"OPEN";if(next!==row.status)await prisma.$executeRawUnsafe(`UPDATE "guild_calls" SET status=$2,updated_at=now() WHERE id=$1`,callId,next);return next as CallStatus;}
async function sendWebhook(url:string,content:string,users:string[]=[]){const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content,allowed_mentions:{users}}),cache:"no-store"});if(!response.ok)throw new Error(`Discord webhook returned ${response.status}`);}
async function sendEmbedWebhook(url:string,embed:any){const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({embeds:[embed]}),cache:"no-store"});if(!response.ok)throw new Error(`Discord webhook returned ${response.status}`);}
function appUrl(){return process.env.NEXT_PUBLIC_APP_URL||(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:"");}
async function getWebhookForGuild(guildId:string){const rows=await prisma.$queryRawUnsafe<Array<{callsWebhookUrl:string|null}>>(`SELECT "callsWebhookUrl" FROM "GuildNotificationConfig" WHERE "guildId"=$1 LIMIT 1`,guildId).catch(()=>[]);return rows[0]?.callsWebhookUrl??null;}
async function getWebhookForCall(call:any){return await getWebhookForGuild(call.guild_id)||call.discord_webhook_url||null;}
function serverTime(value:any){return new Date(value).toLocaleString("en-MY",{timeZone:"Asia/Kuala_Lumpur",dateStyle:"medium",timeStyle:"short"});}
async function getCallDetails(callId:string){const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT c.*,u.username AS creator_username FROM "guild_calls" c JOIN "User" u ON u.id=c.creator_user_id WHERE c.id=$1`,callId);const call=rows[0];if(!call)return null;const requirements=await prisma.$queryRawUnsafe<any[]>(`SELECT id,requirement,quantity FROM "guild_call_requirements" WHERE call_id=$1 ORDER BY created_at`,callId);const participants=await prisma.$queryRawUnsafe<any[]>(`SELECT p.requirement_id,p.status,p.job,m."characterName",m."discordUsername",m."discordUserId" FROM "guild_call_participants" p JOIN "GuildMember" m ON m.id=p.member_id WHERE p.call_id=$1 ORDER BY p.signed_up_at`,callId);return {call,requirements,participants};}
export async function announceNewCall(callId:string){await ensureCallTables();const details=await getCallDetails(callId);const call=details?.call;if(!call)return;const webhook=await getWebhookForCall(call);if(!webhook||call.status==="CANCELLED")return;const {requirements}=details!;const total=requirements.reduce((sum,r)=>sum+Number(r.quantity),0);const url=`${appUrl()}/guild/calls/${encodeURIComponent(callId)}`;const fields=requirements.map(r=>({name:`${r.requirement} × ${r.quantity}`,value:`${r.quantity===1?"1 slot":""}`.trim()||"Required",inline:true}));await sendEmbedWebhook(webhook,{title:`⚔️  CALL TO ARMS  •  ${call.title}`,description:call.description?`${call.description}\n\n**📅 ${serverTime(call.start_at)} (UTC+7 Server Time)**\n**👥 ${total} ${total===1?"player":"players"} required**\n**✦ Created by ${call.creator_username}**`:`**📅 ${serverTime(call.start_at)} (UTC+7 Server Time)**\n**👥 ${total} ${total===1?"player":"players"} required**\n**✦ Created by ${call.creator_username}**`,color:5793266,fields,footer:{text:"ROOC Guild Suite  •  Sign-ups are open"},timestamp:new Date().toISOString(),url});}
export async function announceFilledCall(callId:string){await ensureCallTables();const details=await getCallDetails(callId);const call=details?.call;const webhook=call?await getWebhookForCall(call):null;if(!call||!webhook||call.announced_at||call.status!=="FILLED")return;const {requirements,participants}=details!;const lines=requirements.map(r=>`${r.requirement} × ${r.quantity}: ${participants.filter(p=>p.requirement_id===r.id&&p.status==="ACTIVE").map(p=>`${p.characterName||p.discordUsername||"Member"}${p.job?` (${p.job})`:""}`).join(", ")||"—"}`);await sendWebhook(webhook,`🎉 **CALL TO ARMS — PARTY READY**\n**${call.title}**\n${serverTime(call.start_at)} (UTC+7 Server Time)\nCreated by ${call.creator_username}\n\n${lines.join("\n")}\n\n👉 ${appUrl()}/guild/calls/${callId}`);await prisma.$executeRawUnsafe(`UPDATE "guild_calls" SET announced_at=now(),discord_webhook_url=$2,updated_at=now() WHERE id=$1`,callId,webhook);}
export async function sendReminder(callId:string){await ensureCallTables();const details=await getCallDetails(callId);const call=details?.call;const webhook=call?await getWebhookForCall(call):null;if(!call||!webhook||call.reminder_sent_at||!["FILLED","CONFIRMED"].includes(call.status))return;const {participants}=details!;const mentions=participants.filter(p=>p.status==="ACTIVE").map(p=>p.discordUserId?`<@${p.discordUserId}>`:(p.characterName||p.discordUsername||"Member")).join(" ");await sendWebhook(webhook,`⏰ **CALL TO ARMS — 30 MINUTES**\n**${call.title}**\nStarts: ${serverTime(call.start_at)} (UTC+7 Server Time)\n\n${mentions}\n\n👉 ${appUrl()}/guild/calls/${callId}`);await prisma.$executeRawUnsafe(`UPDATE "guild_calls" SET reminder_sent_at=now(),discord_webhook_url=$2,updated_at=now() WHERE id=$1`,callId,webhook);}
