"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { JOBS } from "@/lib/constants/jobs";

const SERVER_TIME_ZONE = "Asia/Bangkok";
function formatServerTime(value: string) { return new Date(value).toLocaleString("en-GB", { timeZone: SERVER_TIME_ZONE, dateStyle: "medium", timeStyle: "short" }); }
function localInputToServerIso(value: string) { return new Date(`${value}:00+07:00`).toISOString(); }

type Call = { id: string; title: string; description?: string | null; startAt: string; status: string; creatorUsername: string; requiredCount: number | string; activeCount: number | string; signedUp: boolean };
type Requirement = { requirement: string; quantity: number };

async function readJson(response: Response) { const text = await response.text(); if (!text) throw new Error(`Server returned an empty response (${response.status}).`); try { return JSON.parse(text); } catch { throw new Error(`Server returned an invalid response (${response.status}).`); } }

export default function CallsClient({ canManageDiscord }: { canManageDiscord: boolean }) {
  const [calls, setCalls] = useState<Call[]>([]); const [showCreate, setShowCreate] = useState(false); const [showSettings, setShowSettings] = useState(false); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { setLoading(true); setMessage(""); try { const response = await fetch("/api/guild/calls", { cache: "no-store" }); const data = await readJson(response); if (!response.ok) throw new Error(data.error ?? "Failed to load calls."); setCalls(data.calls ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to load calls."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  return <main className="min-h-screen bg-zinc-950 px-4 py-6 text-white md:px-6"><div className="mx-auto max-w-6xl"><Link href="/" className="mb-5 inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white">← Back to Dashboard</Link><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium uppercase tracking-widest text-zinc-500">Guild Activity</p><h1 className="mt-1 text-3xl font-bold">Call To Arms</h1><p className="mt-2 text-sm text-zinc-400">Create and join dungeon or event parties with the exact jobs you need.</p></div><div className="flex gap-2"><button onClick={() => setShowCreate(true)} className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-black hover:bg-zinc-200">+ Create Call</button>{canManageDiscord && <button onClick={() => setShowSettings(true)} className="rounded-lg border border-zinc-700 px-4 py-2.5 text-sm font-medium text-white hover:bg-zinc-800">Discord</button>}</div></div>{message && <div className="mt-5 rounded-lg border border-zinc-700 bg-zinc-900 p-3 text-sm text-zinc-300">{message}</div>}<div className="mt-8 grid gap-4 md:grid-cols-2">{loading ? <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-10 text-center text-zinc-500 md:col-span-2">Loading calls...</div> : calls.length === 0 ? <div className="rounded-2xl border border-dashed border-zinc-700 bg-zinc-900/50 p-10 text-center text-zinc-500 md:col-span-2">No upcoming calls. Create the first one.</div> : calls.map((call) => <Link key={call.id} href={`/guild/calls/${encodeURIComponent(call.id)}`} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5 transition hover:border-zinc-600 hover:bg-zinc-900/80"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-white">{call.title}</h2><p className="mt-1 text-sm text-zinc-400">{formatServerTime(call.startAt)} <span className="text-zinc-600">(UTC+7 Server Time)</span></p></div><Status status={call.status} /></div><p className="mt-4 text-sm text-zinc-400 line-clamp-2">{call.description || "No description."}</p><div className="mt-5 flex items-center justify-between text-xs"><span className="text-zinc-500">Created by {call.creatorUsername}</span><span className={Number(call.activeCount) >= Number(call.requiredCount) ? "text-emerald-400" : "text-zinc-300"}>{call.activeCount} / {call.requiredCount} filled</span></div></Link>)}</div>{showCreate && <CreateModal onClose={() => setShowCreate(false)} onCreated={(id) => { setShowCreate(false); if (id) window.location.assign(`/guild/calls/${encodeURIComponent(id)}`); else { setMessage("Call was created, but no call ID was returned. Refresh the Call To Arms page."); load(); } }} />}{showSettings && <DiscordSettings onClose={() => setShowSettings(false)} onSaved={(configured) => { setShowSettings(false); setMessage(configured ? "Discord notifications configured." : "Discord notifications disabled."); }} />}</div></main>;
}

function CreateModal({ onClose, onCreated }: { onClose: () => void; onCreated: (id: string) => void }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [startAt, setStartAt] = useState(""); const [requirements, setRequirements] = useState<Requirement[]>([{ requirement: "DPS", quantity: 1 }]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/guild/calls", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, description, startAt: localInputToServerIso(startAt), requirements }) }); const data = await readJson(response); if (!response.ok) throw new Error(data.error ?? "Failed to create call."); if (!data.id) throw new Error("The call was created but the server did not return a call ID."); onCreated(String(data.id)); } catch (error) { setError(error instanceof Error ? error.message : "Failed to create call."); } finally { setSaving(false); } }
  return <Modal title="Create Call To Arms" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Event / Dungeon"><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Endless Tower" className="input" /></Field><Field label="Date & Time (Server Time — UTC+7)"><input required type="datetime-local" value={startAt} onChange={(e) => setStartAt(e.target.value)} className="input" /><p className="mt-1 text-xs text-zinc-500">Enter the event time in server time (UTC+7). Your computer's local timezone will not be used.</p></Field><Field label="Description"><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={3} className="input" placeholder="Optional details..." /></Field><Field label="Required Party"><div className="space-y-2">{requirements.map((r, index) => <div key={index} className="flex gap-2"><select value={r.requirement} onChange={(e) => setRequirements(requirements.map((x, i) => i === index ? { ...x, requirement: e.target.value } : x))} style={{ colorScheme: "dark" }} className="input flex-1 bg-zinc-900 text-white"><option value="DPS" className="bg-zinc-900 text-white">DPS</option>{JOBS.map((job) => <option key={job} value={job} className="bg-zinc-900 text-white">{job}</option>)}</select><input min={1} max={50} type="number" value={r.quantity} onChange={(e) => setRequirements(requirements.map((x, i) => i === index ? { ...x, quantity: Number(e.target.value) } : x))} className="input w-20" /><button type="button" onClick={() => setRequirements(requirements.filter((_, i) => i !== index))} className="rounded-lg border border-zinc-700 px-3 text-zinc-400 hover:text-white">×</button></div>)}<button type="button" onClick={() => setRequirements([...requirements, { requirement: "DPS", quantity: 1 }])} className="text-sm text-zinc-400 hover:text-white">+ Add requirement</button></div></Field>{error && <p className="text-sm text-red-400">{error}</p>}<div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{saving ? "Creating..." : "Open Sign-ups"}</button></div></form></Modal>;
}

function DiscordSettings({ onClose, onSaved }: { onClose: () => void; onSaved: (configured: boolean) => void }) { const [url, setUrl] = useState(""); const [configured, setConfigured] = useState(false); const [saving, setSaving] = useState(false); useEffect(() => { fetch("/api/guild/calls/settings").then(readJson).then((d) => setConfigured(Boolean(d.configured))).catch(() => setConfigured(false)); }, []); async function save() { setSaving(true); try { const r = await fetch("/api/guild/calls/settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ webhookUrl: url }) }); const d = await readJson(r); if (r.ok) onSaved(d.configured); else throw new Error(d.error ?? "Failed to save Discord settings."); } catch (error) { alert(error instanceof Error ? error.message : "Failed to save Discord settings."); } finally { setSaving(false); } } return <Modal title="Discord Notifications" onClose={onClose}><p className="text-sm text-zinc-400">{configured ? "A webhook is currently configured." : "No webhook is configured."} Paste a Discord channel webhook URL to announce full parties and send 30-minute reminders.</p><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://discord.com/api/webhooks/..." className="input" /><div className="flex justify-between"><button onClick={() => setUrl("")} className="text-sm text-zinc-500 hover:text-white">Clear / disable</button><button onClick={save} disabled={saving} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">{saving ? "Saving..." : "Save"}</button></div></Modal>; }

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-2xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose} className="text-2xl text-zinc-500 hover:text-white">×</button></div>{children}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-zinc-500">{label}</span>{children}</label>; }
function Status({ status }: { status: string }) { const label = status === "FILLED" ? "FULL" : status; return <span className="rounded-full border border-zinc-700 bg-zinc-800 px-2.5 py-1 text-[11px] font-semibold text-zinc-300">{label}</span>; }