"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const SERVER_TIME_ZONE = "Asia/Bangkok";
function formatServerTime(value: string) { return new Date(value).toLocaleString("en-GB", { timeZone: SERVER_TIME_ZONE, dateStyle: "medium", timeStyle: "short" }); }
type Requirement = { id: string; requirement: string; quantity: number };
type Participant = { id: string; requirementId: string; status: string; characterName?: string; discordUsername?: string; discordUserId?: string; job?: string; memberId: string };
type Call = { id: string; title: string; description?: string | null; startAt: string; status: string; creatorUsername: string; requiredCount: number | string; activeCount: number | string };
type Data = { call: Call; requirements: Requirement[]; participants: Participant[]; signedUp: boolean; webhookConfigured: boolean; canManage: boolean };

export default function CallDetailClient({ id }: { id: string }) {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { const r = await fetch(`/api/guild/calls/${id}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) setError(d.error ?? "Failed to load call."); else setData(d); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load call."); } }
  useEffect(() => { load(); }, [id]);
  async function action(body: object) { setBusy(true); setError(""); try { const r = await fetch(`/api/guild/calls/${id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) setError(d.error ?? "Action failed."); else await load(); } catch (e) { setError(e instanceof Error ? e.message : "Action failed."); } finally { setBusy(false); } }
  if (!data) return <main className="min-h-screen bg-zinc-950 p-8 text-white"><Link href="/guild/calls" className="text-sm text-zinc-400 hover:text-white">← Back to Call To Arms</Link><p className="mt-8 text-zinc-500">{error || "Loading..."}</p></main>;
  const { call, requirements, participants } = data;
  return <main className="min-h-screen bg-zinc-950 px-4 py-6 text-white md:px-6"><div className="mx-auto max-w-5xl"><Link href="/guild/calls" className="mb-5 inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white">← Back to Call To Arms</Link><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-3xl font-bold">{call.title}</h1><span className="rounded-full border border-zinc-700 bg-zinc-800 px-2.5 py-1 text-xs text-zinc-300">{call.status === "FILLED" ? "FULL" : call.status}</span></div><p className="mt-2 text-zinc-400">{formatServerTime(call.startAt)} <span className="text-zinc-600">(UTC+7 Server Time)</span> · Created by {call.creatorUsername}</p>{call.description && <p className="mt-4 whitespace-pre-wrap text-sm text-zinc-300">{call.description}</p>}</div><div className="text-right"><div className="text-3xl font-bold">{call.activeCount} / {call.requiredCount}</div><div className="text-xs uppercase tracking-wide text-zinc-500">Party filled</div></div></div></div>
    {error && <div className="mt-4 rounded-lg border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}
    <section className="mt-6 space-y-4">{requirements.map((req) => { const active = participants.filter((p) => p.requirementId === req.id && p.status === "ACTIVE"); const waitlist = participants.filter((p) => p.requirementId === req.id && p.status === "WAITLIST"); return <div key={req.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">{req.requirement}</h2><span className="text-sm text-zinc-400">{active.length} / {req.quantity}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{active.map((p) => <div key={p.id} className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2"><div className="font-medium">{p.characterName || p.discordUsername || "Member"}</div><div className="text-xs text-zinc-500">{p.job || "Job not set"}</div></div>)}{active.length < req.quantity && <div className="rounded-lg border border-dashed border-zinc-700 px-3 py-2 text-sm text-zinc-500">Slot available</div>}</div>{waitlist.length > 0 && <div className="mt-4 border-t border-zinc-800 pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Waitlist</p><div className="mt-2 space-y-1">{waitlist.map((p, index) => <div key={p.id} className="text-sm text-zinc-400">{index + 1}. {p.characterName || p.discordUsername || "Member"} <span className="text-xs text-zinc-600">({p.job || "Job not set"})</span></div>)}</div></div>}</div>; })}</section>
    <section className="mt-6 flex flex-wrap gap-2">{!data.signedUp && !["CANCELLED", "COMPLETED"].includes(call.status) && requirements.map((req) => <button key={req.id} disabled={busy} onClick={() => action({ action: "signup", requirementId: req.id })} className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-50">Join as {req.requirement}</button>)}{data.signedUp && !["CANCELLED", "COMPLETED"].includes(call.status) && <button disabled={busy} onClick={() => action({ action: "leave" })} className="rounded-lg border border-zinc-700 px-4 py-2.5 text-sm hover:bg-zinc-800">Leave Call</button>}{data.canManage && call.status === "FILLED" && <button disabled={busy} onClick={() => action({ action: "confirm" })} className="rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-50">Confirm Party</button>}{data.canManage && !["CANCELLED", "COMPLETED"].includes(call.status) && <button disabled={busy} onClick={() => action({ action: "cancel" })} className="rounded-lg border border-red-900 px-4 py-2.5 text-sm text-red-300 hover:bg-red-950/40 disabled:opacity-50">Cancel Call</button>}<button disabled={busy} onClick={load} className="rounded-lg border border-zinc-700 px-4 py-2.5 text-sm hover:bg-zinc-800">Refresh</button></section>
  </div></main>;
}
