import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { getCurrentAuth, hasPermission } from "@/lib/auth";
import { hasGuildModule, RESOURCE_SUITE_MODULE } from "@/lib/auth/modules";
import { getGuildSubscriptionEntitlement } from "@/lib/billing/entitlement-status";
import { getPlatformAdmin } from "@/lib/platform-admin";

const DISCORD_URL = "https://discord.gg/NrT2RKnh8M";
const SERVER_TIME_ZONE = "Asia/Bangkok";

export default async function Home() {
  const auth = await getCurrentAuth();
  if (!auth) return <PublicLanding />;
  const isPlatformAdmin = Boolean(await getPlatformAdmin());
  const subscription = await getGuildSubscriptionEntitlement(auth.guild.id);
  const hasResourceSuite = await hasGuildModule(auth.guild.id, RESOURCE_SUITE_MODULE);
  const guild = await prisma.guild.findUnique({ where: { id: auth.guild.id }, include: { members: { where: { active: true }, orderBy: { updatedAt: "desc" }, take: 6 }, resources: { where: { active: true } }, reservedAllocations: true, allocationRuns: { orderBy: { createdAt: "desc" }, take: 5, include: { event: true, bidPages: true } }, events: { orderBy: { date: "desc" }, take: 5, include: { rosters: true } }, _count: { select: { members: { where: { active: true } } } } } });
  const canViewAllocation = hasResourceSuite && hasPermission(auth.role, "allocation.view");
  const canViewApplicants = hasPermission(auth.role, "applicants.view");
  const ownMember = await prisma.guildMember.findFirst({ where: { guildId: auth.guild.id, userId: auth.user.id, active: true }, select: { id: true, characterName: true } });

  const serverToday = new Intl.DateTimeFormat("en-CA", { timeZone: SERVER_TIME_ZONE, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const todayStart = new Date(`${serverToday}T00:00:00+07:00`);
  const tomorrowStart = new Date(todayStart.getTime() + 24 * 60 * 60 * 1000);
  const activeMemberCount = guild?._count.members ?? 0;
  const membersOnLeaveToday = guild ? await prisma.memberLeave.count({ where: { member: { guildId: guild.id, active: true }, date: { gte: todayStart, lt: tomorrowStart } } }) : 0;
  const availableToday = Math.max(0, activeMemberCount - membersOnLeaveToday);
  const applicantCount = canViewApplicants ? await prisma.guildApplicant.count({ where: { guildId: auth.guild.id, status: "PENDING" } }) : 0;
  const eventsToday = await prisma.event.count({ where: { guildId: auth.guild.id, date: { gte: todayStart, lt: tomorrowStart } } });

  const memberActivity = (guild?.members ?? []).map((member) => ({ date: member.updatedAt, title: member.characterName || member.discordUsername || "Member", detail: member.job ? `Member profile updated · ${member.job}` : "Member profile updated", href: `/guild/members/${member.id}` }));
  const leaveActivity = guild ? await prisma.memberLeave.findMany({ where: { member: { guildId: guild.id } }, orderBy: { createdAt: "desc" }, take: 5, include: { member: { select: { id: true, characterName: true, discordUsername: true } } } }) : [];
  const rosterActivity = (guild?.events ?? []).flatMap((event) => event.rosters.map((roster) => ({ date: roster.createdAt, title: "Roster generated", detail: `${formatEventType(event.type)} · ${roster.name}`, href: `/events/${event.id}` })));
  const biddingActivity = (guild?.allocationRuns ?? []).flatMap((run) => run.bidPages.map((page) => ({ date: page.createdAt, title: "Bidding generated", detail: `${page.type} bid page · Page ${page.pageNumber}`, href: "/bid-pages" })));
  const applicantRecords = canViewApplicants ? await prisma.guildApplicant.findMany({ where: { guildId: auth.guild.id }, orderBy: { createdAt: "desc" }, take: 10, select: { characterName: true, discordUsername: true, status: true, createdAt: true, decidedAt: true } }) : [];
  const applicantActivity = applicantRecords.flatMap((applicant) => { const name = applicant.characterName || applicant.discordUsername || "Applicant"; const applied = [{ date: applicant.createdAt, title: name, detail: "Application submitted", href: "/guild/applicants" }]; if (!applicant.decidedAt || applicant.status === "PENDING") return applied; const decision = applicant.status === "ACCEPTED" ? "Application accepted" : "Application rejected"; return [...applied, { date: applicant.decidedAt, title: name, detail: decision, href: "/guild/applicants" }]; });
  const leaveItems = leaveActivity.map((leave) => ({ date: leave.createdAt, title: leave.member.characterName || leave.member.discordUsername || "Member", detail: "Leave recorded", href: `/guild/members/${leave.member.id}` }));
  const recentMemberActivity = memberActivity.sort((a, b) => b.date.getTime() - a.date.getTime()).slice(0, 5);
  const recentLeaveActivity = leaveItems.slice(0, 5);
  const recentRosterActivity = [...rosterActivity, ...biddingActivity].sort((a, b) => b.date.getTime() - a.date.getTime()).slice(0, 5);
  const recentApplicantActivity = applicantActivity.sort((a, b) => b.date.getTime() - a.date.getTime()).slice(0, 5);
  return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-7xl px-6 py-10">
    <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="mb-2 text-sm font-medium uppercase tracking-widest text-zinc-500">ROO Guild Suite</p><h1 className="text-4xl font-bold tracking-tight">Guild Dashboard</h1><p className="mt-2 text-zinc-400">Manage your guild, events, rosters, resources and allocations.</p></div><div className="flex items-center gap-3"><span className="max-w-40 truncate text-sm text-zinc-300">{auth.user.username}</span>{isPlatformAdmin && <Link href="/admin" className="rounded-lg border border-zinc-700 px-3 py-1.5 text-xs font-medium text-zinc-300 transition hover:border-zinc-500 hover:bg-zinc-800 hover:text-white">Admin</Link>}<form action="/api/auth/logout" method="POST"><button type="submit" className="rounded-lg border border-zinc-700 px-3 py-1.5 text-xs font-medium text-zinc-300 transition hover:border-zinc-500 hover:bg-zinc-800 hover:text-white">Log out</button></form></div></header>
      {!guild ? <section className="rounded-2xl border border-dashed border-zinc-700 bg-zinc-900/50 p-10 text-center"><h2 className="text-xl font-semibold">No guild configured</h2><p className="mt-2 text-sm text-zinc-400">Your ROO Guild Suite database is connected, but no guild has been created yet.</p><Link href="/guild" className="mt-6 inline-flex rounded-lg bg-white px-5 py-3 font-medium text-black">Configure Guild</Link></section> : <>
      <section className="mb-6 rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><p className="text-sm text-zinc-500">Guild</p><h2 className="mt-1 text-2xl font-semibold">{guild.name}</h2><p className="mt-1 text-sm text-zinc-500">Discord Guild ID: {guild.discordGuildId}</p></section>
      <section className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Available today (not on leave)" value={availableToday} /><StatCard label="Num of Applicants" value={applicantCount} /><StatCard label="Events today" value={eventsToday} /></section>
      <section className="mb-6 rounded-2xl border border-zinc-700 bg-zinc-900 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium uppercase tracking-widest text-zinc-500">Your Character</p><h2 className="mt-1 text-xl font-semibold">{ownMember?.characterName ?? "Member profile"}</h2><p className="mt-1 text-sm text-zinc-400">Keep your ROO stats up to date by uploading your latest character screenshots.</p></div>{ownMember ? <div className="flex flex-wrap gap-2"><Link href={`/guild/members/ocr?memberId=${ownMember.id}`} className="inline-flex w-fit rounded-lg bg-white px-5 py-2.5 text-sm font-medium text-black transition hover:bg-zinc-200">Update stats via OCR →</Link><Link href="/guild/members/leave" className="inline-flex w-fit rounded-lg border border-zinc-700 px-5 py-2.5 text-sm font-medium text-white transition hover:border-zinc-500 hover:bg-zinc-800">Apply Leave</Link></div> : <Link href="/guild/members" className="inline-flex w-fit rounded-lg border border-zinc-700 px-5 py-2.5 text-sm font-medium text-white transition hover:border-zinc-500 hover:bg-zinc-800">View member profile</Link>}</div></section>
      <section className="mt-10"><div className="mb-4"><h2 className="text-lg font-semibold">Activity</h2><p className="mt-1 text-sm text-zinc-500">Recent member, leave, applicant, roster and bidding activity.</p></div><div className={`grid gap-4 ${canViewApplicants ? "lg:grid-cols-4" : "lg:grid-cols-3"}`}><ActivityPanel title="Member Activity" items={recentMemberActivity} empty="No recent member activity." /><ActivityPanel title="Leave" items={recentLeaveActivity} empty="No leave records yet." />{canViewApplicants && <ActivityPanel title="Applicants" items={recentApplicantActivity} empty="No applicant activity yet." />}<ActivityPanel title="Roster & Bidding" items={recentRosterActivity} empty="No rosters or bidding pages generated yet." /></div></section>
      {hasPermission(auth.role, "events.view") && <section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Events & Rosters</h2><p className="mt-1 text-sm text-zinc-500">Manage events, generate rosters and organize parties.</p></div><Link href="/events" className="text-sm font-medium text-zinc-400 hover:text-white">View all →</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CompactDashboardLink href="/events" title="Events" description="Create and manage Guild League and Emperium Overrun events." /><CompactDashboardLink href="/events?view=rosters" title="Rosters" description="View events with rosters, generate automatic rosters and manage party assignments." /><CompactDashboardLink href="/events?view=preferred" title="Preferred Rosters" description="Manage preferred roster arrangements used as the starting point for future events." /><CompactDashboardLink href="/guild/calls" title="Call To Arms" description="Create and join dungeon or event parties, fill required jobs and manage waitlists." /></div></section>}
      {(hasPermission(auth.role, "members.view") || hasPermission(auth.role, "users.view") || hasPermission(auth.role, "guild.manage") || canViewApplicants) && <section className="mt-10"><h2 className="mb-4 text-lg font-semibold">Guild Management</h2><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{hasPermission(auth.role, "members.view") && <CompactDashboardLink href="/guild/members" title="Members" description="Manage guild members, eligibility, priority and character information." />}{hasPermission(auth.role, "members.view") && <CompactDashboardLink href="/guild/rankings" title="Guild Rankings" description="Compare overall, DPS, Tank and PvP performance across the guild." />}{hasPermission(auth.role, "members.view") && <CompactDashboardLink href="/guild/statistics" title="Guild Statistics" description="View guild performance, member composition and activity statistics." />}{canViewApplicants && <CompactDashboardLink href="/guild/applicants" title="Applicants" description="Generate recruitment links and review applicant ROO stats, scores and projected guild percentile." />}{canViewAllocation && <CompactDashboardLink href="/guild/resources" title="Resources" description="Manage feathers, cards and resource limits." />}{canViewAllocation && <CompactDashboardLink href="/guild/reservations" title="Reservations" description="Manage reserved resource allocations." />}{hasPermission(auth.role, "users.view") && <CompactDashboardLink href="/guild/users" title="Users" description="View Discord accounts and their guild access." />}{hasPermission(auth.role, "guild.manage") && <CompactDashboardLink href="/guild" title="Guild Settings" description="Configure your guild and Discord server." />}</div></div></section>}
      {canViewAllocation && <section className="mt-10"><h2 className="mb-4 text-lg font-semibold">Allocation</h2><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><CompactDashboardLink href="/allocation" title="Allocation" description="Preview and run the next resource allocation." /><CompactDashboardLink href="/allocation/history" title="Allocation History" description="Review previous allocation runs, results and bidding pages." /><CompactDashboardLink href="/guild/resources/history" title="Resource Allocation History" description="See which resources were distributed to which members and when." />{hasResourceSuite && <CompactDashboardLink href="/bid-pages" title="Bid Pages" description="View active and previous bidding pages and find assigned slots." />}</div></div></section>}
      <section className="mt-10 border-t border-zinc-800 pt-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-zinc-500">Subscription</p><div className="mt-1 flex flex-wrap items-center gap-3"><h2 className="text-lg font-semibold">{subscription.planName ?? "No active subscription"}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${subscription.enabled ? "bg-emerald-950 text-emerald-300" : "bg-red-950 text-red-300"}`}>{subscription.enabled ? "Active" : "Inactive"}</span>{subscription.cancelAtPeriodEnd && subscription.enabled && <span className="rounded-full bg-amber-950 text-amber-300">Cancels at period end</span>}</div><p className="mt-1 text-sm text-zinc-500">{subscription.expiresAt ? `${subscription.cancelAtPeriodEnd ? "Access until" : "Renews"} ${formatDate(subscription.expiresAt)}` : subscription.enabled ? "No expiry date" : "Renew to restore full guild access."}</p></div><Link href="/billing/new" className="inline-flex w-fit rounded-lg border border-zinc-700 px-4 py-2.5 text-sm font-medium text-white transition hover:border-zinc-500 hover:bg-zinc-800">Manage subscription →</Link></div></section>
      {subscription.warning && subscription.daysRemaining !== null && <section className="mt-4 rounded-2xl border border-amber-800/60 bg-amber-950/30 p-5"><h2 className="font-semibold text-amber-200">{subscription.planName ?? "Subscription"} expires in {subscription.daysRemaining} {subscription.daysRemaining === 1 ? "day" : "days"}</h2><p className="mt-1 text-sm text-amber-100/70">Renew before expiry to keep your guild accessible. {subscription.cancelAtPeriodEnd ? "Your subscription is scheduled to cancel at the end of this period." : ""}</p><Link href="/billing/new" className="mt-3 inline-flex rounded-lg bg-amber-200 px-4 py-2 text-sm font-medium text-zinc-950 hover:bg-amber-100">Manage subscription</Link></section>}
    </>}</div></main>;
}

function PublicLanding() { return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto flex min-h-screen max-w-6xl flex-col px-6 py-8 sm:px-10"><header className="flex items-center justify-between"><Link href="/" className="text-2xl font-bold tracking-tight">HMDL</Link><a href={DISCORD_URL} target="_blank" rel="noreferrer" className="text-sm text-zinc-400 transition hover:text-white">Discord ↗</a></header><section className="flex flex-1 flex-col justify-center py-16"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-medium uppercase tracking-[0.35em] text-zinc-500">HEIMDALL · HMDL</p><h1 className="mt-5 text-5xl font-bold tracking-tight sm:text-7xl">Guild management,<br />without the mess.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">Manage members, events, rosters, resources, bidding and allocation in one place — built for modern guilds.</p></div><div className="mx-auto mt-14 grid w-full max-w-4xl gap-4 md:grid-cols-3"><LandingCard href="/pricing" title="New User" description="Explore HMDL packages and features, then get started with your guild." action="View packages →" /><LandingCard href="/login" title="Login" description="Already using HMDL? Sign in with Discord and continue to your guild." action="Continue with Discord →" /><a href={DISCORD_URL} target="_blank" rel="noreferrer" className="group rounded-2xl border border-zinc-800 bg-zinc-900 p-7 transition hover:border-zinc-600 hover:bg-zinc-800"><div className="flex items-start justify-between gap-4"><h2 className="text-xl font-semibold">Discord</h2><span className="text-zinc-600 transition group-hover:translate-x-1 group-hover:text-zinc-300">↗</span></div><p className="mt-3 min-h-14 text-sm leading-6 text-zinc-400">Join the HMDL community for announcements, support, updates and discussion.</p><p className="mt-7 text-sm font-semibold text-white">Join HMDL Discord →</p></a></div></section><footer className="border-t border-zinc-900 py-5 text-center text-xs text-zinc-600">HMDL · Heimdall</footer></div></main>; }
function LandingCard({ href, title, description, action }: { href: string; title: string; description: string; action: string }) { return <Link href={href} className="group rounded-2xl border border-zinc-800 bg-zinc-900 p-7 transition hover:border-zinc-600 hover:bg-zinc-800"><div className="flex items-start justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><span className="text-zinc-600 transition group-hover:translate-x-1 group-hover:text-zinc-300">→</span></div><p className="mt-3 min-h-14 text-sm leading-6 text-zinc-400">{description}</p><p className="mt-7 text-sm font-semibold text-white">{action}</p></Link>; }
function StatCard({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>; }
function CompactDashboardLink({ href, title, description }: { href: string; title: string; description: string }) { return <Link href={href} className="group flex min-h-16 items-center justify-between gap-4 rounded-xl border border-zinc-800 bg-zinc-950/40 px-4 py-3 transition hover:border-zinc-700 hover:bg-zinc-800"><div className="min-w-0"><p className="font-medium text-zinc-100">{title}</p><p className="mt-0.5 line-clamp-1 text-xs text-zinc-500 group-hover:text-zinc-400">{description}</p></div><span className="shrink-0 text-zinc-600 transition group-hover:translate-x-0.5 group-hover:text-zinc-300">→</span></Link>; }
function ActivityPanel({ title, items, empty }: { title: string; items: { date: Date; title: string; detail: string; href: string }[]; empty: string }) { return <div className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900"><div className="border-b border-zinc-800 px-5 py-4"><h3 className="font-semibold">{title}</h3></div>{items.length > 0 ? <div className="divide-y divide-zinc-800">{items.map((item, index) => <Link key={`${item.href}-${item.date.getTime()}-${index}`} href={item.href} className="flex items-center gap-3 px-5 py-4 transition hover:bg-zinc-800"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="mt-1 truncate text-xs text-zinc-500">{item.detail}</p></div><time className="shrink-0 text-xs text-zinc-500">{formatRelative(item.date)}</time></Link>)}</div> : <div className="p-5 text-sm text-zinc-500">{empty}</div>}</div>; }
function formatEventType(type: string) { switch (type) { case "GUILD_LEAGUE": return "Guild League"; case "EMPERIUM_OVERRUN": return "Emperium Overrun"; default: return type; } }
function formatDate(date: Date) { return new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: SERVER_TIME_ZONE }).format(date); }
function formatRelative(date: Date) { const diff = Date.now() - date.getTime(); const minutes = Math.floor(diff / 60000); if (minutes < 1) return "just now"; if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; const days = Math.floor(hours / 24); if (days < 7) return `${days}d ago`; return formatDate(date); }
